version: "3.8"
services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=zino
      - POSTGRES_PASSWORD=sakata_gintoki
    volumes:
      - postgres:/var/lib/postgresql/kakeibo
    ports:
      - "5439:5432"
volumes:
  postgres:
