version: "3.8"
services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=zino
      - POSTGRES_PASSWORD=sakata_gintoki
      - POSTGRES_DB=kakeibo
    volumes:
      - postgres:/var/lib/postgresql/kakeibo
    ports:
      - "5434:5432"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data
volumes:
  postgres:
  redisDB:
